name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # 添加此行，允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:   # 定义作业所需的权限, 这是使用 OIDC (Trusted Publishing) 的关键
      
      id-token: write   # 允许生成新的OIDC身份令牌并读取令牌
     
      contents: read    # 允许检出代码库内容

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install .
        playwright install --with-deps

    - name: Build package
      run: python -m build

    # 发布包到 PyPI： 使用 PyPA (Python Packaging Authority) 官方提供的 'pypi-publish' Action
    # 这个 Action 会自动处理 OIDC 认证（因为上面设置了 permissions.id-token: write）
    # 它会查找 'dist' 文件夹下的包文件并上传
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1